name: Playwright Tests
# Trigger Playwright CI workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Debug: List of tests  

      - name: Run CucumberRegression
        run: npm run CucumberRegression

      - name: Run Web Tests
        run: npm run webTests
        
      - name: Run API Tests
        run: npm run APITests
        
      - name: Run API Storage Tests
        run: npm run APIstorageSession     

      # Debug: List root directory files after test run
      - name: List root directory files after tests
        run: ls -la

      # Debug: List contents of playwright-report if it exists
      - name: List playwright-report folder contents if it exists
        run: |
          if [ -d "playwright-report" ]; then
            echo "playwright-report folder exists, contents:"
            ls -la playwright-report
          else
            echo "playwright-report folder does not exist."
          fi

      # Zip the report folder only if it exists
      - name: Zip Playwright HTML report if it exists
        if: always()
        run: |
          if [ -d "playwright-report" ]; then
            echo "Zipping report..."
            zip -r playwright-report.zip playwright-report
            echo "Zipped file info:"
            ls -la playwright-report.zip
          else
            echo "No playwright-report folder found to zip."
          fi

      # Upload zipped artifact only if created
      - name: Upload Playwright report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
